"""add severity column

Revision ID: 5ffe9fc3c4d3
Revises: 
Create Date: 2017-04-10 23:42:46.207606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffe9fc3c4d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shamelog', sa.Column('severity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shamelog', 'severity')
    # ### end Alembic commands ###
